### ISSUE TITLE
DELETE Customer request expects Customer JSON response

### ISSUE THREAD

**Issue by smur89** [gocardless/gocardless-pro-java#49]
When executing this code on an existing customer:
```Scala
client.customers.remove(identity).execute
```

The call is executed and the customer removed correctly, as confirmed in the UI. However the client is expecting the API to return a Customer JSON object, and fails on parsing this. On further inspection of the API docs, this endpoint does indeed return `204 No Content`. 

```Stacktrace
Not a JSON Object: null
java.lang.IllegalStateException: Not a JSON Object: null
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)
	at com.gocardless.http.ResponseParser.parseSingle(ResponseParser.java:28)
	at com.gocardless.http.DeleteRequest.parseResponse(DeleteRequest.java:38)
	at com.gocardless.http.HttpClient.parseResponseBody(HttpClient.java:159)
	at com.gocardless.http.HttpClient.execute(HttpClient.java:88)
	at com.gocardless.http.HttpClient$1.call(HttpClient.java:108)
	at com.github.rholder.retry.AttemptTimeLimiters$NoAttemptTimeLimit.call(AttemptTimeLimiters.java:78)
	at com.github.rholder.retry.Retryer.call(Retryer.java:160)
	at com.gocardless.http.HttpClient.executeWithRetries(HttpClient.java:112)
	at com.gocardless.http.DeleteRequest.execute(DeleteRequest.java:21)
```

I expect the issue lies in the Type parameter [here](https://github.com/gocardless/gocardless-pro-java/blob/cd5a6d0e6d2b66532a5e4b9e8d506f333fda4375/src/main/java/com/gocardless/services/CustomerService.java#L770) which should be some version of `Unit`/`void`. This may be the case for similar resources, I have only tested with customers so far. 

Seems like [these tests](https://github.com/gocardless/gocardless-pro-java/blob/3fa3b45dfb243188d9ad99e6eaac80b495ea3e28/src/test/java/com/gocardless/http/DeleteRequestTest.java) are not really up to date or in line with the actual responses from the server.

For now, I have worked around the issue with this and would consider creating our own scala client for this perhaps
```Scala
def deleteCustomer(customerId: String): F[Unit] = Try(client.customers.remove(customerId).execute).fold({
      case e: IllegalStateException if e.getMessage == "Not a JSON Object: null" => F.unit
      case e => F.raiseError(e)
    }, _ => F.unit)
```

Using version `4.0.0` of this library.

**Comment by vdandugc** [comment]
This is fixed by lates release 4.8.0
