### ISSUE TITLE
Unexpected metadata form

### ISSUE THREAD

**Issue by mjaggard** [gocardless/gocardless-pro-java#73]
I'm using Google GSON to parse a notification sent by GoCardless into a `List<com.gocardless.resources.Event>` but I'm seeing errors like the below - it seems that Event defines metadata as a Map but I'm actually getting a String in the data?

```
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 300 path $.events[0].metadata
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 300 path $.events[0].metadata
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at com.mycompany.gateways.gocardless.GoCardlessWebHookService.handleEvent(GoCardlessWebHookService.java:36)
```

**Comment by mjaggard** [comment]
For reference, I have a class like this:

```
public class EventWrapper {
    private List<Event> events;
}
```

and then I use `EventWrapper wrapper = gson.fromJson(rawDataFromNotification, EventWrapper.class);`
